local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Welcome text", name: "body", widget: "markdown"}
      - file: "contact.html"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Contact Instructions", name: "body", widget: "markdown"}
